# Generated by Django 4.1.5 on 2025-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=10)),
                ('mno', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=200)),
            ],
        ),
    ]
